### ISSUE TITLE
mytardis-salt: Invalid model identifier: 'tardis_portal.location'

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#383]
Not sure if mytardis-salt issues go here (in "mytardis")?  I couldn't see an Issues list on the mytardis-salt GitHub page.

I just tried the easy MyTardis Salt installation, as described on mytardis.org, and I encountered the following error:

```
----------
          ID: load-fixtures
    Function: cmd.run
        Name: bin/django loaddata locations.json
      Result: False
     Comment: Command "bin/django loaddata locations.json" run
     Started: 05:32:31.500550
    Duration: 715.753 ms
     Changes:
              ----------
              pid:
                  3129
              retcode:
                  1
              stderr:
                  DeserializationError: Problem installing fixture '/opt/mytardis/develop/tardis/tardis_portal/fixtures/locations.json': Invalid model identifier: 'tardis_portal.location'
              stdout:
```
